### ISSUE TITLE
Customer Survey

### ISSUE THREAD

**Issue by rfoucard** [TYPO3-Initiatives/structured-content#5]
- [x] Prepare the questions
- [x] Choose the tool
- [x] Prepare the mailing list
- [x] Send the survey to developers/integrators
- [x] Send the survey to editors

- [Survey DE](https://drive.google.com/open?id=1LuW2X1jrX6lr_n1cSQdJzpYb2TrRQUuPH3PlN4KI3vc)
- [Survey EN](https://drive.google.com/open?id=183g8BnCnO4IBnUKARBpGcDQsGgCoHgqkpJ0AeflowPY)

- [x] Process the results 
- [x] Publish the results

**Comment by typecat** [comment]
The surveys are closed and the results evaluated. They will be published as an article typo3.org shortly.
